services:
  postgres:
    image: postgres:17
    container_name: postgres_restore

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2DAMAD
      POSTGRES_DB: postgres

    ports:
      - "15432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: {}